/**
 * @generated by contrib/devtools/chainparams/generate_chainparams_constants.py
 */

#include <chainparamsconstants.h>

namespace ChainParamsConstants {
    const BlockHash MAINNET_DEFAULT_ASSUME_VALID = BlockHash::fromHex("000000000008e3132221cd11676e410bda33bee14103efc0fed29feb30975ed2");
    const uint256 MAINNET_MINIMUM_CHAIN_WORK = uint256S("00000000000000000000000000000000000000000000000035bbdea100247cec");
    const uint64_t MAINNET_ASSUMED_BLOCKCHAIN_SIZE = 1;
    const uint64_t MAINNET_ASSUMED_CHAINSTATE_SIZE = 1;

    const BlockHash TESTNET_DEFAULT_ASSUME_VALID = BlockHash::fromHex("0000000004e5242ccdd7ff82f9aa180c6bfdb1a657882c5f660e9f9d5378e446");
    const uint256 TESTNET_MINIMUM_CHAIN_WORK = uint256S("00000000000000000000000000000000000000000000000000067b7a1b323f4e");
    const uint64_t TESTNET_ASSUMED_BLOCKCHAIN_SIZE = 1;
    const uint64_t TESTNET_ASSUMED_CHAINSTATE_SIZE = 1;
} // namespace ChainParamsConstants

